"""public-legacy.css: the slice of the dashboard's styles.css that public pages still use.

Generated by extracting every styles.css rule that matches something on the public pages
(or a class their scripts add), then checked pixel-for-pixel against the full stylesheet on
desktop and mobile. If a public page needs another legacy rule, add it here rather than
re-linking the 170 KB styles.css.
"""
from pathlib import Path

LEGACY = Path("app/static/public-legacy.css")


def test_subset_is_small():
    assert LEGACY.exists()
    assert LEGACY.stat().st_size < 40_000 < Path("app/static/styles.css").stat().st_size


def test_review_detail_route_uses_the_subset():
    source = Path("app/routers/reviews.py").read_text(encoding="utf-8")
    assert "/static/public-legacy.css?v=" in source and "/styles.css" not in source


def test_subset_keeps_the_rules_public_pages_rely_on():
    css = LEGACY.read_text(encoding="utf-8")
    for selector in (".auth-form", ".faq-question", ".faq-answer", ".review-report"):
        assert selector in css, selector
    assert css.count("{") == css.count("}")
