"""Versioned editorial recommendations. No user content or ratings are published here."""
TRAILS = {
    "finding-your-feet": {
        "name": "Finding your feet", "tag": "BEGIN AGAIN",
        "intro": "Four stories about starting over without pretending that a new beginning is effortless. Pick the format that suits your evening; this is a menu, not a completion challenge.",
        "guide": "Start with Kiki for a self-contained story, Stardew when you want to participate in making a home, Walter Mitty for a nudge toward a small adventure, or Earthsea for the sharper edge of growing into responsibility.",
        "prompt": "What did this make you want to begin, and what could you let yourself learn slowly?",
        "items": [
            {"key": "kiki", "category": "anime", "title": "Kiki's Delivery Service", "meta": {"year": 1989},
             "why": "A young witch starts a delivery business away from home. The useful connection here is between finding work and finding confidence: competence is something built through ordinary encounters. Choose this entry for a story with a clear stopping point, especially if a long series feels like another obligation.",
             "caveat": "Gentle does not mean free of tension: expect self-doubt and a perilous rescue. This is an anime film, saved in the Anime tab.",
             "source": "https://www.ghibli.jp/works/majo/"},
            {"key": "stardew", "category": "video-games", "title": "Stardew Valley", "meta": {},
             "why": "The farm gives starting over a physical shape: a patch cleared, seeds planted, a neighbor met. Pair it with Kiki to compare two kinds of independence, one watched and one practiced. Set a small goal for your first session, such as learning the route to town, rather than treating every in-game day as an efficiency test.",
             "caveat": "An open-ended game can become a large time commitment. Its clock and resource management may feel busy if you want completely unstructured relaxation.",
             "source": "https://www.stardewvalley.net/about/"},
            {"key": "walter-mitty", "category": "movies", "title": "The Secret Life of Walter Mitty", "meta": {"director": "Ben Stiller", "year": 2013},
             "why": "This is the most outward-facing choice in the trail: a daydreamer begins taking small, concrete risks. It pairs well with Stardew's slower progress because both make a life change feel like a series of approachable next steps.",
             "caveat": "A glossy, sentimental adventure-comedy whose tone may be too neat if you want a realistic portrait of change.",
             "source": "https://www.20thcenturystudios.com/movies/the-secret-life-of-walter-mitty"},
            {"key": "earthsea", "category": "books", "title": "A Wizard of Earthsea", "meta": {"author": "Ursula K. Le Guin", "year": 1968},
             "why": "Ged's apprenticeship offers the sharper edge of this collection. Learning is not just accumulating ability; it involves recognizing limits and taking responsibility. Place it after the lighter entries when you want to question the idea that becoming more capable automatically makes life simpler. Try noting how your impression of Ged changes as you read.",
             "caveat": "Expect danger and darker themes, with a deliberate, mythic storytelling style. This is not a cozy substitute for the other two entries.",
             "source": "https://www.penguinrandomhouse.com/books/827671/ursula-k-le-guin-the-complete-earthsea-volume-one-loa-400-by-ursula-k-le-guin--brian-attebery-editor/"},
        ],
    },
    "notice-the-details": {
        "name": "Notice the details", "tag": "LOOK CLOSER",
        "intro": "A film, documentary series, ambient album, and book offer four different exercises in attention. This trail is for an evening when you want something to think about afterward, without another sprawling universe to track.",
        "guide": "Choose After Yang for an uninterrupted viewing session, Abstract for one creative discipline, Music for Airports for listening without plot, or Braiding Sweetgrass for a slower change in perspective. You do not need to consume all four together.",
        "prompt": "Which small detail would you have missed if you had been rushing?",
        "items": [
            {"key": "yang", "category": "movies", "title": "After Yang", "meta": {"director": "Kogonada", "year": 2022},
             "why": "A family's effort to repair an android opens a story about memory and connection. The science-fiction premise is a doorway into an intimate question: how much of someone else's life do we actually notice? Pair it with Abstract to shift from attending to remembered details to attending to the decisions behind everyday objects.",
             "caveat": "A reflective drama involving loss, rather than action-led science fiction. Saved with its 2022 US release year; some catalogs list its 2021 premiere.",
             "source": "https://a24films.com/films/after-yang"},
            {"key": "abstract", "category": "tv-shows", "title": "Abstract: The Art of Design", "meta": {"year": 2017},
             "why": "This documentary series puts creative practice in the foreground. Start with a discipline you rarely think about, and ask what problem the designer is actually solving. It provides a practical companion to the film's attention to detail: a designed object can carry choices you stop seeing once it becomes familiar.",
             "caveat": "Episodes focus on different disciplines, so their appeal will vary. Treat this as a set of starting points, not a comprehensive course in design.",
             "source": "https://www.netflix.com/title/80057883"},
            {"key": "airports", "category": "music", "title": "Ambient 1: Music for Airports", "meta": {"artist": "Brian Eno", "year": 1978},
             "why": "Eno's layered loops offer attention without demanding that you follow a narrative. Listen once while doing something quiet, then give a passage your full attention. The contrast is the point of this pairing: the same sound can function as surroundings or become the main event, depending on how you approach it.",
             "caveat": "An instrumental ambient album with repetition and little conventional song structure. It may not fit a mood that calls for lyrics or a strong beat.",
             "source": "https://shop.brian-eno.net/collections/music/products/ambient-1-music-for-airports-vinyl-2lp"},
            {"key": "braiding-sweetgrass", "category": "books", "title": "Braiding Sweetgrass", "meta": {"author": "Robin Wall Kimmerer", "year": 2013},
             "why": "Kimmerer joins botany, Indigenous knowledge, and lived observation in essays that repeatedly ask you to reconsider what counts as a relationship. Read one chapter at a time and take its invitations to pay attention literally.",
             "caveat": "A reflective nonfiction collection, not a quick how-to book. Its blend of science, memoir, and spirituality may land differently for different readers.",
             "source": "https://milkweed.org/book/braiding-sweetgrass"},
        ],
    },
    "small-adventures": {
        "name": "Small adventures, big heart", "tag": "GO GENTLY",
        "intro": "For when you want a change of scenery without an exhausting quest. These are companionable adventures with room for humor, detours, and a warm place to return to.",
        "guide": "Pick Paddington 2 for pure lift, Laid-Back Camp for a low-stakes series, A Short Hike for a game you can finish in an evening, or The Hobbit for the archetypal there-and-back-again journey.",
        "prompt": "What made the journey feel welcoming rather than merely busy?",
        "items": [
            {"key": "paddington-2", "category": "movies", "title": "Paddington 2", "meta": {"director": "Paul King", "year": 2017},
             "why": "Paddington treats every new person as someone worth meeting, which turns a caper into a case for ordinary decency. It is a good reset when you want charm with actual comic momentum.",
             "caveat": "Very sweet and family-oriented, even when its plot becomes a prison-break farce.", "source": "https://www.paddington.com/"},
            {"key": "laid-back-camp", "category": "anime", "title": "Laid-Back Camp", "meta": {"year": 2018},
             "why": "Camping plans, warm meals, and landscape photography are the plot in the best possible sense. Each episode models a modest outing that feels complete without becoming a competition.",
             "caveat": "Deliberately low-conflict and slow-paced. Choose another trail if you want escalating stakes.", "source": "https://yurucamp.jp/"},
            {"key": "short-hike", "category": "video-games", "title": "A Short Hike", "meta": {},
             "why": "A little island, a summit, and plenty of invitations to wander make this a rare game that respects a short session. Let yourself follow the odd path instead of optimizing the route uphill.",
             "caveat": "A compact exploration game with light platforming; its small scale is a feature, not a promise of dozens of hours.", "source": "https://ashorthike.com/"},
            {"key": "hobbit", "category": "books", "title": "The Hobbit", "meta": {"author": "J. R. R. Tolkien", "year": 1937},
             "why": "Bilbo's adventure works because he brings his homebody instincts along with him. Its episodic structure makes it easy to pause, and its curiosity about riddles, meals, and strange people keeps the stakes human-sized.",
             "caveat": "A classic children's fantasy with older prose rhythms and a few scenes that may feel more dated than the newer entries here.", "source": "https://www.tolkienestate.com/writing/the-hobbit/"},
        ],
    },
    "clever-mysteries": {
        "name": "Clever mysteries", "tag": "FOLLOW THE CLUES",
        "intro": "Four mysteries that reward attention without demanding a corkboard. Each has a distinct rhythm: a whodunit, a case-of-the-week show, a quietly surreal anime, and a page-turning ensemble novel.",
        "guide": "Start with Knives Out for a complete movie-night puzzle. Let Poker Face be your episodic option, Odd Taxi your patient slow-burn, and The Thursday Murder Club your social reading pick.",
        "prompt": "Which clue mattered because of where it appeared, rather than what it was?",
        "items": [
            {"key": "knives-out", "category": "movies", "title": "Knives Out", "meta": {"director": "Rian Johnson", "year": 2019},
             "why": "A lavish family gathering gives this whodunit plenty of motives, but the fun is in watching the story revise what you thought you knew. It is an excellent shared watch because the mystery invites conversation before it reveals its hand.",
             "caveat": "Contains a death, family cruelty, and some broad comic caricature alongside its light-on-its-feet tone.", "source": "https://www.lionsgate.com/movies/knives-out"},
            {"key": "poker-face", "category": "tv-shows", "title": "Poker Face", "meta": {"year": 2023},
             "why": "This series reveals the culprit early, then makes the pleasure about how its observant lead will prove it. The format is generous: one satisfying case at a time, with a larger journey only lightly threaded underneath.",
             "caveat": "A crime series with violence and some grim circumstances, even when its style is playful.", "source": "https://www.peacocktv.com/stream-tv/poker-face"},
            {"key": "odd-taxi", "category": "anime", "title": "Odd Taxi", "meta": {"year": 2021},
             "why": "A taxi driver's apparently unrelated passengers become a finely interlocked mystery. Give it a few episodes to establish its strange conversational rhythm; the details it plants early are the reason it belongs here.",
             "caveat": "Despite its animal character designs, it deals with crime, isolation, and mature themes.", "source": "https://oddtaxi.jp/"},
            {"key": "thursday-murder-club", "category": "books", "title": "The Thursday Murder Club", "meta": {"author": "Richard Osman", "year": 2020},
             "why": "Four retirement-village friends turn a hobby of investigating old cases into a live mystery. Its real pleasure is the group chemistry: clues are shared between people who have learned how to surprise one another.",
             "caveat": "The warm, witty tone sits beside murder, grief, and illness; it is cozier than it is consequence-free.", "source": "https://www.penguin.co.uk/books/313038/the-thursday-murder-club-by-osman-richard/9780241988268"},
        ],
    },
    "found-family": {
        "name": "Found family", "tag": "MAKE ROOM",
        "intro": "These picks are about people becoming each other's shelter, often imperfectly and often by accident. The shared idea is not that family is easy, but that care can be practiced.",
        "guide": "Choose Hunt for the Wilderpeople for a sharp standalone comedy, The Bear when you want an intense ensemble, Spy x Family for warmth with a comic premise, or Lauryn Hill for a record shaped by voice and self-definition.",
        "prompt": "What form of care did the characters have to learn rather than simply feel?",
        "items": [
            {"key": "wilderpeople", "category": "movies", "title": "Hunt for the Wilderpeople", "meta": {"director": "Taika Waititi", "year": 2016},
             "why": "A foster child and reluctant guardian become a makeshift team in the New Zealand bush. Its jokes never erase the fact that both characters are learning how to be wanted, which gives the adventure its real momentum.",
             "caveat": "Includes grief, child welfare themes, and bursts of danger beneath a comic exterior.", "source": "https://www.searchlightpictures.com/huntforthewilderpeople/"},
            {"key": "the-bear", "category": "tv-shows", "title": "The Bear", "meta": {"year": 2022},
             "why": "A restaurant becomes the site where grief, talent, and old resentments collide. Watch when you want a group dynamic that is earned through work rather than instantly comforting; every act of coordination matters.",
             "caveat": "High-stress, loud, and emotionally intense, with depictions of grief, addiction, and family conflict.", "source": "https://www.fxnetworks.com/shows/the-bear"},
            {"key": "spy-family", "category": "anime", "title": "Spy x Family", "meta": {"year": 2022},
             "why": "A spy, assassin, and telepathic child build a household under false pretenses, then find that the routine of caring for one another starts to become real. It is a breezy option with room for genuine affection.",
             "caveat": "Stylized spy violence and occasional mature jokes sit alongside its broadly family-friendly comedy.", "source": "https://spy-family.net/"},
            {"key": "miseducation", "category": "music", "title": "The Miseducation of Lauryn Hill", "meta": {"artist": "Lauryn Hill", "year": 1998},
             "why": "Hill's debut moves between romance, faith, confidence, and hard-earned self-knowledge. Listen for the way the record makes vulnerability feel communal rather than passive; it gives this trail a voice that belongs to itself.",
             "caveat": "Contains explicit lyrics and emotionally direct material about relationships and betrayal.", "source": "https://www.laurynhill.com/"},
        ],
    },
    "beautifully-strange-worlds": {
        "name": "Beautifully strange worlds", "tag": "STEP SIDEWAYS",
        "intro": "A set of worlds that feel fully imagined without burying you under lore. Each asks you to notice its rules by living alongside them for a while.",
        "guide": "Spirited Away is the complete visual feast; Mushishi is the episodic quiet option; Outer Wilds asks you to investigate a world yourself; Piranesi is the most intimate and literary doorway in.",
        "prompt": "What rule of this world did you understand only after seeing its consequences?",
        "items": [
            {"key": "spirited-away", "category": "movies", "title": "Spirited Away", "meta": {"director": "Hayao Miyazaki", "year": 2001},
             "why": "A bathhouse for spirits supplies endlessly specific images, but Chihiro's growing steadiness keeps the strangeness grounded. It rewards a rewatch because the background is crowded with visual rules and tiny acts of kindness.",
             "caveat": "Includes frightening transformations, peril, and a few intense images that may be too much for very young viewers.", "source": "https://www.ghibli.jp/works/chihiro/"},
            {"key": "mushishi", "category": "anime", "title": "Mushishi", "meta": {"year": 2005},
             "why": "A wandering healer investigates life-forms that sit just beyond ordinary perception. Its anthology structure makes each episode feel like a folktale observed with care, rather than a chapter in a lore-heavy saga.",
             "caveat": "Very quiet, contemplative storytelling with melancholy cases and a slow pace.", "source": "https://www.mushishi-anime.com/"},
            {"key": "outer-wilds", "category": "video-games", "title": "Outer Wilds", "meta": {},
             "why": "Knowledge is your only lasting upgrade in this solar-system mystery. Follow a question that genuinely interests you and resist looking up solutions too early; discovery is the game's emotional engine.",
             "caveat": "Spaceflight controls, time pressure, and existential themes can be disorienting. Avoid spoilers for the intended experience.", "source": "https://www.mobiusdigitalgames.com/outer-wilds.html"},
            {"key": "piranesi", "category": "books", "title": "Piranesi", "meta": {"author": "Susanna Clarke", "year": 2020},
             "why": "A solitary narrator maps an immense house of halls, tides, statues, and mysteries. Go in with as little plot knowledge as possible and let the narrator's careful observations teach you how to read the place.",
             "caveat": "A short, deliberately disorienting fantasy with themes of manipulation and isolation.", "source": "https://us.macmillan.com/books/9781635575637/piranesi"},
        ],
    },
    "one-evening-well-spent": {
        "name": "One evening, well spent", "tag": "PRESS PLAY",
        "intro": "A practical trail for the moment you want something excellent but do not want to start a huge commitment. Every pick has a satisfying first sitting, whether or not you continue afterward.",
        "guide": "Before Sunset is the concentrated film choice, The Good Place has a breezy first episode, Florence is a short interactive story, and Blue works as one unbroken listening session.",
        "prompt": "Did the limited time make you pay attention differently?",
        "items": [
            {"key": "before-sunset", "category": "movies", "title": "Before Sunset", "meta": {"director": "Richard Linklater", "year": 2004},
             "why": "Two people spend one afternoon catching up, and the film trusts conversation to carry the stakes. It is a compact watch that asks what a life looks like when viewed through a single unfinished connection.",
             "caveat": "Dialogue-driven and bittersweet, with more adult romantic reflection than plot movement.", "source": "https://www.warnerbros.com/movies/before-sunset"},
            {"key": "good-place", "category": "tv-shows", "title": "The Good Place", "meta": {"year": 2016},
             "why": "A dead woman wakes up in an afterlife neighborhood that may not have the right person. Its first episode is funny on its own, while the show's question about how people become better gives you a reason to keep going.",
             "caveat": "A comedy about death and moral failure that becomes more serialized as it goes. Avoid plot summaries if you continue.", "source": "https://www.nbc.com/the-good-place"},
            {"key": "florence", "category": "video-games", "title": "Florence", "meta": {},
             "why": "This interactive story reduces a relationship to small gestures: a conversation becoming easier, a routine shared, a memory held. It is ideal when you want a complete emotional arc without a long control-learning curve.",
             "caveat": "A brief, linear game about romance and heartbreak; expect roughly an hour, not a replay-heavy experience.", "source": "https://annapurnainteractive.com/en/games/florence"},
            {"key": "blue", "category": "music", "title": "Blue", "meta": {"artist": "Joni Mitchell", "year": 1971},
             "why": "Blue's spareness makes each lyric and arrangement feel close-up without becoming small. Give it the room of a full album listen, then notice how often an ordinary image becomes a pressure point.",
             "caveat": "Emotionally direct songs about love, loneliness, and uncertainty. Best heard when you are open to a quieter mood.", "source": "https://jonimitchell.com/music/album.cfm?id=13"},
        ],
    },
    "weather-and-windows": {
        "name": "Weather and windows", "tag": "STAY A WHILE",
        "intro": "Rain, rooms, cities at night, and the feeling of observing life from one step removed. This is a mood trail for patient works that make atmosphere part of the story.",
        "guide": "In the Mood for Love is the richest visual watch, The Garden of Words is its concise animated counterpart, Punisher is the late-night album, and The Memory Police is the most unsettling reading choice.",
        "prompt": "How did the setting change what the characters could say out loud?",
        "items": [
            {"key": "in-the-mood-for-love", "category": "movies", "title": "In the Mood for Love", "meta": {"director": "Wong Kar-wai", "year": 2000},
             "why": "Two neighbors suspect their spouses are having an affair and find themselves sharing a careful, suspended intimacy. Repeated spaces, clothing, music, and weather make the unsaid part of the drama.",
             "caveat": "A slow, melancholy romantic drama about infidelity and restraint; its emotional power is mostly subtext.", "source": "https://www.criterion.com/films/198-in-the-mood-for-love"},
            {"key": "garden-of-words", "category": "anime", "title": "The Garden of Words", "meta": {"year": 2013},
             "why": "Rain delays two strangers into the same garden, where conversation becomes a shelter from their separate difficulties. Its short running time makes it a useful counterpoint to the film's longer, more formal ache.",
             "caveat": "Contains an age-gap relationship context and emotional distress; it is visually lush but not uncomplicated comfort viewing.", "source": "https://en.shinkaiworks.com/film/kotonoha.html"},
            {"key": "punisher", "category": "music", "title": "Punisher", "meta": {"artist": "Phoebe Bridgers", "year": 2020},
             "why": "Bridgers uses deadpan detail and spacious arrangements to make private anxieties feel strangely architectural. Listen for the images that recur and the way a joke can turn into an admission before the song is over.",
             "caveat": "Contains explicit lyrics and themes of depression, grief, and self-harm. Save it for the right emotional weather.", "source": "https://www.phoebefuckingbridgers.com/"},
            {"key": "memory-police", "category": "books", "title": "The Memory Police", "meta": {"author": "Yoko Ogawa", "year": 1994},
             "why": "On an island where objects disappear and forgetting is enforced, a novelist tries to preserve what can still be named. Its clear prose and dreamlike repetition make absence feel physical rather than abstract.",
             "caveat": "A quiet dystopia involving state coercion, loss, and disturbing violence. Not a cozy rainy-day read despite its atmosphere.", "source": "https://www.penguinrandomhouse.com/books/607196/the-memory-police-by-yoko-ogawa/"},
        ],
    },
    "make-something": {
        "name": "Make something", "tag": "USE YOUR HANDS",
        "intro": "Creative work is often more interesting once you see the revisions, mishaps, and patience behind it. These picks are for getting out of the passive-scroll mindset and back into making.",
        "guide": "Jiro Dreams of Sushi offers craft at its most exacting, The Great Pottery Throw Down turns learning into friendly television, Chicory lets you make marks immediately, and The Creative Act gives you a book to dip into between attempts.",
        "prompt": "What part of the process looked different after you saw the work behind it?",
        "items": [
            {"key": "jiro", "category": "movies", "title": "Jiro Dreams of Sushi", "meta": {"director": "David Gelb", "year": 2011},
             "why": "This portrait of a Tokyo sushi master is compelling less as food tourism than as a study of repetition, standards, and apprenticeship. Use it as a prompt to notice one small skill you could practice with more attention.",
             "caveat": "Its devotion to mastery can feel demanding, and it contains discussion of aging, succession, and an exacting workplace culture.", "source": "https://www.magpictures.com/jirodreamsofsushi/"},
            {"key": "pottery-throw-down", "category": "tv-shows", "title": "The Great Pottery Throw Down", "meta": {"year": 2015},
             "why": "A competition format becomes unusually kind when contestants share techniques, fix disasters, and celebrate each other's work. It is an easy way to see how material constraints can lead to inventive decisions.",
             "caveat": "A reality competition with eliminations; availability and season order vary by region.", "source": "https://www.bbc.co.uk/programmes/b09qy65b"},
            {"key": "chicory", "category": "video-games", "title": "Chicory: A Colorful Tale", "meta": {},
             "why": "A coloring-book world lets you draw directly onto the landscape, then makes that simple act part of its story about creative pressure. Experiment badly on purpose; the game is more generous when you stop trying to make every mark permanent.",
             "caveat": "Includes frank depictions of anxiety, depression, and creative burnout, alongside its playful art style.", "source": "https://www.chicorygame.com/"},
            {"key": "creative-act", "category": "books", "title": "The Creative Act", "meta": {"author": "Rick Rubin", "year": 2023},
             "why": "Rubin's short reflections are built for opening at random before a creative session. Treat them as prompts rather than rules: write down the one idea that feels useful, then close the book and make something.",
             "caveat": "A philosophical, aphoristic book rather than a concrete craft manual. Readers wanting step-by-step instruction may find it too abstract.", "source": "https://www.penguinrandomhouse.com/books/717356/the-creative-act-by-rick-rubin/"},
        ],
    },
    "distant-futures": {
        "name": "Distant futures, human scale", "tag": "IMAGINE OTHERWISE",
        "intro": "Science fiction is most useful when the future changes the angle on the present. These picks make large ideas personal: language, ecosystems, work, companionship, and the kinds of societies people build.",
        "guide": "Arrival is the accessible movie-night entry, Scavengers Reign is the strange ecosystem watch, Citizen Sleeper is the role-playing choice, and The Left Hand of Darkness is the classic to sit with slowly.",
        "prompt": "Which future detail felt less like prediction and more like a question about the present?",
        "items": [
            {"key": "arrival", "category": "movies", "title": "Arrival", "meta": {"director": "Denis Villeneuve", "year": 2016},
             "why": "First contact becomes a question of translation, patience, and what language makes imaginable. It is a great entry point for people who want big science-fiction ideas held inside an emotional, legible story.",
             "caveat": "Includes grief, military tension, and an intentionally nonlinear structure. Go in ready to listen as closely as the characters do.", "source": "https://www.paramountmovies.com/movies/arrival"},
            {"key": "scavengers-reign", "category": "tv-shows", "title": "Scavengers Reign", "meta": {"year": 2023},
             "why": "Stranded humans try to survive on a planet whose ecology has no reason to accommodate them. Every creature and landscape feels like a problem with its own logic, making this a visual companion to Outer Wilds with much higher stakes.",
             "caveat": "Animated but emphatically adult, with body horror, violence, and frequent peril.", "source": "https://www.max.com/shows/scavengers-reign/3e2e5bb4-e439-4aa9-9724-32a52c4997d1"},
            {"key": "citizen-sleeper", "category": "video-games", "title": "Citizen Sleeper", "meta": {},
             "why": "A digitized worker escapes to a rough space station and survives by building relationships under pressure. Its tabletop-inspired choices make solidarity feel practical: who gets your time, and what do you owe yourself?",
             "caveat": "Contains poverty, illness, coercion, and resource pressure. Its reading-heavy format suits players who enjoy narrative decisions.", "source": "https://www.fellowtraveller.games/citizen-sleeper"},
            {"key": "left-hand-darkness", "category": "books", "title": "The Left Hand of Darkness", "meta": {"author": "Ursula K. Le Guin", "year": 1969},
             "why": "An envoy tries to understand a planet whose society unsettles his inherited assumptions about gender, loyalty, and politics. Read it for the friction between perspective and reality, not for a fast plot alone.",
             "caveat": "A classic with deliberately measured pacing and dated aspects of its narrator's viewpoint, though those limits are part of the discussion it invites.", "source": "https://www.ursulakleguin.com/the-left-hand-of-darkness"},
        ],
    },
}
